# Build Debian Stretch image.

FROM debian:stretch

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  systemd \
  ansible

RUN mkdir -p /usr/ansible-test
WORKDIR /usr/ansible-test

COPY . /usr/ansible-test
