---
- name: Include OS specific configuration
  include_vars: "{{ item }}"
  with_first_found:
    - paths:
        - "vars"
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      skip: yes

- name: Install
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Set up configuration file
  template:
    src: templates/nftables.rules.j2
    dest: "{{ nftables_config_file }}"
    owner: root
    group: root
    mode: 0644
# '--check' is not available on current major distros. Disabling temporarily.
#    validate: "nft --check --file %s"
  notify: Reload nftables

- name: Disable conflicting services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  register: disable_service_result
  failed_when: (disable_service_result is failed)
               and ('Could not find the requested service' not in disable_service_result.msg)
  with_items:
    - iptables

- name: Start service
  service:
    name: nftables
    state: started

- name: Enable service
  service:
    name: nftables
    enabled: yes
...
